services:
  # Main backend service
  - type: web
    name: video-downloader-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YOUTUBE_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: PINCHFLAT_URL
        value: https://pinchflat-service.onrender.com  # Will be set after Pinchflat deploys
    
  # Pinchflat service (runs as separate Docker service)
  - type: web
    name: pinchflat-service
    env: docker
    dockerfilePath: ./Dockerfile.pinchflat
    envVars:
      - key: TZ
        value: Europe/Bucharest
      - key: LOG_LEVEL
        value: info
      - key: YT_DLP_WORKER_CONCURRENCY
        value: "2"
    ports:
      - "8945"
    volumes:
      - name: pinchflat-config
        mountPath: /config
      - name: pinchflat-downloads
        mountPath: /downloads

# Persistent volumes for Pinchflat
volumes:
  - name: pinchflat-config
    mountPath: /config
    sizeGB: 1
  - name: pinchflat-downloads
    mountPath: /downloads
    sizeGB: 10