services:
  - type: web
    name: video-downloader-pro
    env: node
    plan: starter
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
      chmod +x yt-dlp
      ls -la yt-dlp
      echo "yt-dlp downloaded and made executable"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YT_DLP_PATH
        value: ./yt-dlp